#!/usr/bin/env python

import sys
import os
import subprocess

exana_dir = os.environ['EXANA_DIR']
pin_dir = os.environ['PIN_DIR']

#cmd = pin_dir + "/pin -t "+ pin_dir + "/source/tools/Exana/obj-intel64/Exana.so -cacheConfig " + exana_dir + "/cache.config"

cmd= pin_dir+"/pin -t "+ exana_dir + "/pintool/Exana.so -cacheConfig "+exana_dir+"/cache.config"


args = sys.argv
for i in range(1, len(args)):
	cmd += ' ' + args[i]

subprocess.call(cmd, shell=True)
