#!/usr/bin/env python

import sys
import os
import subprocess

dir = os.environ['EXANA_DIR']

cmd=dir+"/util/ExanaView/exanav"

args = sys.argv
for i in range(1, len(args)):
	cmd += ' ' + args[i]

subprocess.call(cmd, shell=True)
